version: "3.3"

services:
    webstatic:
        build:
            context:    ./web-static
        image: web/static
        container_name: webstatic
    webui:
        build:
            context:    ./web-ui
        image: web/ui
        container_name: webui
    proxy:
        image: "haproxy:alpine"
        depends_on:
            - webstatic
            - webui
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        ports:
            - "9000:9000"
        container_name: haproxy